export const FLIGHT_ROUTES = [
  {
    routeCode: "VJ1234",
    airline: "VietJet Air",
    logo: "https://rubee.com.vn/wp-content/uploads/2021/05/Logo-vietjet.jpg", // Placeholder image
    departureTime: "08:00",
    arrivalTime: "10:10",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 130, // 2h 10m converted to minutes
    originalPrice: 1499616,
    discountedPrice: 1424636,
    planeCode: "A320",
  },
  {
    routeCode: "VN5678",
    airline: "Vietnam Airlines",
    logo: "https://www.etrip4u.com/Content/userfiles/logo-vietnam-airlines-lich-su-hinh-thanh-va-y-nghia-3.png",
    departureTime: "09:30",
    arrivalTime: "11:45",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 135, // 2h 15m converted to minutes
    originalPrice: 1650000,
    discountedPrice: 1600000,
    planeCode: "A321",
  },
  {
    routeCode: "BAM9012",
    airline: "Bamboo Airways",
    logo: "https://inkythuatso.com/uploads/thumbnails/800/2021/09/logo-bamboo-airways-inkythuatso-13-16-29-54.jpg",
    departureTime: "11:15",
    arrivalTime: "13:25",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 130, // 2h 10m converted to minutes
    originalPrice: 1550000,
    discountedPrice: 1500000,
    planeCode: "A321",
  },
  {
    routeCode: "PA3456",
    airline: "Pacific Airlines",
    logo: "https://www.pacific-airlines.com/uploads/images/news/pacific-airlines-logo.png",
    departureTime: "13:00",
    arrivalTime: "15:05",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 125, // 2h 05m converted to minutes
    originalPrice: 1400000,
    discountedPrice: 1350000,
    planeCode: "A320",
  },
  {
    routeCode: "VJ5678",
    airline: "VietJet Air",
    logo: "https://rubee.com.vn/wp-content/uploads/2021/05/Logo-vietjet.jpg",
    departureTime: "14:30",
    arrivalTime: "16:40",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 130, // 2h 10m converted to minutes
    originalPrice: 1499616,
    discountedPrice: 1424636,
    planeCode: "A320",
  },
  {
    routeCode: "VN6789",
    airline: "Vietnam Airlines",
    logo: "https://www.etrip4u.com/Content/userfiles/logo-vietnam-airlines-lich-su-hinh-thanh-va-y-nghia-3.png",
    departureTime: "16:30",
    arrivalTime: "18:45",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 135, // 2h 15m converted to minutes
    originalPrice: 1700000,
    discountedPrice: 1650000,
    planeCode: "A321",
  },
  {
    routeCode: "BAM1234",
    airline: "Bamboo Airways",
    logo: "https://inkythuatso.com/uploads/thumbnails/800/2021/09/logo-bamboo-airways-inkythuatso-13-16-29-54.jpg",
    departureTime: "18:00",
    arrivalTime: "20:05",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 125, // 2h 05m converted to minutes
    originalPrice: 1600000,
    discountedPrice: 1550000,
    planeCode: "A321",
  },
  {
    routeCode: "VJ9012",
    airline: "VietJet Air",
    logo: "https://rubee.com.vn/wp-content/uploads/2021/05/Logo-vietjet.jpg",
    departureTime: "19:45",
    arrivalTime: "21:55",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 130, // 2h 10m converted to minutes
    originalPrice: 1499616,
    discountedPrice: 1424636,
    planeCode: "A320",
  },
  {
    routeCode: "PA7890",
    airline: "Pacific Airlines",
    logo: "https://www.pacific-airlines.com/uploads/images/news/pacific-airlines-logo.png",
    departureTime: "20:30",
    arrivalTime: "22:35",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 125, // 2h 05m converted to minutes
    originalPrice: 1480000,
    discountedPrice: 1430000,
    planeCode: "A320",
  },
  {
    routeCode: "VN3456",
    airline: "Vietnam Airlines",
    logo: "https://www.etrip4u.com/Content/userfiles/logo-vietnam-airlines-lich-su-hinh-thanh-va-y-nghia-3.png",
    departureTime: "22:00",
    arrivalTime: "00:15",
    departureCode: "HAN",
    departureName: "Nội Bài",
    arrivalCode: "SGN",
    arrivalName: "Tân Sơn Nhất",
    duration: 135, // 2h 15m converted to minutes
    originalPrice: 1750000,
    discountedPrice: 1700000,
    planeCode: "A321",
  },
];
